apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "bookstore_db"
  BOOK_SERVICE_URL: "http://book-service:5001"
  ORDER_SERVICE_URL: "http://order-service:5002"

